name: "naive"
strategy: "seasonal_naive" 
#   forward_fill (just takes the last value)
#   mean (mean of all values)
#   seasonal_naive (value of same day/hour in previous season)
#   seasonal_average (precition is the average of the whole season before)
season_length: ${dataset.seasonality}