name: "naive"
strategy: "seasonal_naive" # Options: forward_fill, mean, seasonal_naive, seasonal_average
season_length: 5          # Used only for seasonal strategies. 24 for hourly, 7 for daily, etc.