name: "air_quality"
file_path: "data/air_quality.csv"
target_column: "pm2.5"
frequency: "h"
subset_size: 1680    # 10 weeks
test_size: 48        # 2 days
seasonality: 24
context_window: 48   # used for LSTM and XGBoost

prophet_seasonality_mode: "multiplicative"

sarima_order: [1, 0, 3]
sarima_seasonal_order: [0, 0, 0, 24]