name: "energy"
file_path: "data/PJME_hourly.csv"
target_column: "PJME_MW"
frequency: "h"
subset_size: 1680    # 10 weeks
test_size: 48        # 2 days
seasonality: 24
context_window: 48   # used for LSTM and XGBoost

prophet_seasonality_mode: "additive"

sarima_order: [1, 0, 0]
sarima_seasonal_order: [0, 1, 0, 24]