name: "iot_temp"
file_path: "data/iot_temp.csv"
target_column: "temperature"
frequency: "5min"
subset_size: 2016    # 7 days
test_size: 60        # 5 hours
seasonality: 288
context_window: 48   # used for LSTM and XGBoost

prophet_seasonality_mode: "additive"

sarima_order: [1, 1, 2]
sarima_seasonal_order: [0, 0, 0, 0]