name: "sp500"
file_path: "data/SP500_daily.csv"
target_column: "Close" # we only want the closing price (csv files only contains it anyway cause I remove the other columns)
subset_size: 1000
test_size: 5 
seasonality: 5 # 5 active days in a trading week