name: "sp500"
file_path: "data/SP500_daily.csv"
target_column: "Close"
frequency: "B"
subset_size: 1008     # 4 trading years
test_size: 5          # 1 full trading week
seasonality: 5
context_window: 10    # used for LSTM and XGBoost

prophet_seasonality_mode: "multiplicative"

sarima_order: [0, 1, 0]
sarima_seasonal_order: [0, 0, 0, 5]