defaults:
  - _self_
  - dataset: energy
  - corruption: mcar
  - model: xgboost

# A placeholder for terminal overrides. Defaults to nothing.
run_suffix: ""

# Dynamically builds the name (e.g., "pjm_energy_xgboost_mcar")
experiment_name: "${dataset.name}_${corruption.type}_${model.name}${run_suffix}"

seed: 42
num_runs: 25

corruption_start: 0
corruption_end: 40
corruption_step: 1