import numpy as np
import pandas as pd
from sklearn.metrics import mean_absolute_error, mean_squared_error

def evaluate_predictions(true_values: pd.Series, predictions: list[float]) -> dict[str, float]:
    """
    Calculates evaluation metrics comparing ground truth to model predictions.

    Args:
        true_values (pd.Series): Ground truth time-series data.
        predictions (list[float]): Sequential predictions generated by the model.

    Returns:
        dict[str, float]: A dictionary containing 'MAE' and 'RMSE' metrics.
    """
    # Stripping pandas indices via NumPy conversion prevents scikit-learn 
    # from improperly aligning the raw list against the Series index.
    y_true = np.array(true_values, dtype=float)
    y_pred = np.array(predictions, dtype=float)
    
    return {
        "MAE": float(mean_absolute_error(y_true, y_pred)),
        "RMSE": float(np.sqrt(mean_squared_error(y_true, y_pred)))
    }